source "${BASH_SOURCE%/*}/include/meson64_common.inc"
ASOUND_STATE="asound.state.meson64"

CPUMIN=1000000
CPUMAX=1800000
GOVERNOR=ondemand

if [[ $BOARD == radxa-zero ]]; then
	BOOTSOURCE='https://github.com/radxa/u-boot.git'
	BOOTBRANCH='branch:radxa-zero-v2021.01'
	BOOTPATCHDIR='u-boot-radxa-zero'
	BOOTDIR='u-boot-radxa-zero'
fi

uboot_custom_postprocess() {
	if [[ $BOARD == radxa-zero ]]; then
		uboot_g12_postprocess "$SRC"/cache/sources/amlogic-boot-fip/radxa-zero g12a
	fi
}
