#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2013-2026 Igor Pecovnik, igor@armbian.com
#
# This file is a part of the Armbian Build Framework
# https://github.com/armbian/build/
#

declare -g ARCH="riscv64"
declare -g LINUXFAMILY="spacemit-k3"
declare -g GOVERNOR="performance"
declare -g BOOTTAG="k3-br-v1.0.0"

# OpenSBI
declare -g ATFSOURCE="https://github.com/spacemit-com/opensbi.git"
declare -g ATFDIR="opensbi"
declare -g ATFBRANCH="tag:${BOOTTAG}"
declare -g ATF_TARGET_MAP="PLATFORM_DEFCONFIG=k3_defconfig PLATFORM=generic ;;build/platform/generic/firmware/fw_dynamic.itb"

# U-Boot
declare -g BOOTSOURCE="https://github.com/spacemit-com/uboot-2022.10.git"
declare -g BOOTBRANCH="${BOOTBRANCH_BOARD:-"tag:${BOOTTAG}"}"
declare -g BOOTDIR='u-boot-spacemit-k3'
declare -g BOOTPATCHDIR="${BOOTPATCHDIR:-"legacy/u-boot-spacemit-k3"}"
declare -g UBOOT_TARGET_MAP=";;bootinfo_block.bin bootinfo_spinand.bin bootinfo_spinor.bin FSBL.bin fw_dynamic.itb u-boot.itb u-boot-env-default.bin esos.itb partition_4M.json spi-flash-howto.txt"
declare -g BOOTCONFIG="k3_defconfig" # Boot with generic SpacemiT K3 config

# Linux
case "${BRANCH}" in
	legacy)
		declare -g KERNELSOURCE="https://github.com/spacemit-com/linux-6.18.git"
		declare -g KERNELBRANCH="branch:k3-br-v1.0.y"
		declare -g EXTRAWIFI="no" # WiFi drivers are already included in the kernel
		declare -g KERNEL_MAJOR_MINOR="6.18"
		declare -g LINUXCONFIG="linux-${LINUXFAMILY}-legacy"
		;;
	current)
		declare -g KERNELSOURCE="https://gitlab.com/jmontleon/kernel-ark"
		declare -g KERNELBRANCH="branch:fedora-6.18.y-riscv-k3.0"
		declare -g EXTRAWIFI="no" # WiFi drivers are already included in the kernel
		declare -g KERNEL_MAJOR_MINOR="6.18"
		declare -g LINUXCONFIG="linux-${LINUXFAMILY}-current"
		;;
esac

uboot_custom_postprocess() {
	uboot_work_dir="${SRC}/cache/sources/u-boot-worktree/${BOOTDIR}/${BOOTTAG}"
	if [[ -d "${uboot_work_dir}" ]]; then
		display_alert "$BOARD" "Adding ESOS blob" "info"
		cp -fv "${SRC}/packages/blobs/riscv64/spacemit-k3/esos.itb" "${uboot_work_dir}/"
		display_alert "$BOARD" "Adding partition_4M.json file" "info"
		cp -fv "${SRC}/packages/blobs/riscv64/spacemit-k3/partition_4M.json" "${uboot_work_dir}/partition_4M.json"
		display_alert "$BOARD" "Adding SPI flash how-to" "info"
		cp -fv "${SRC}/packages/blobs/riscv64/spacemit-k3/spi-flash-howto.txt" "${uboot_work_dir}/spi-flash-howto.txt"
	fi
}

#pre_prepare_partitions() { # place holder
#	declare -g OFFSET="6" # This is subject to change
#	declare -g IMAGE_PARTITION_TABLE="msdos"
#}

#write_uboot_platform() { # place holder
#	echo ""
#}
