/* this file should be generated by mkcvipart.py,please do not modify this file manually*/

#ifndef CVIPART_H
#define CVIPART_H
#ifndef CONFIG_ENV_IS_NOWHERE
#define CONFIG_ENV_IS_NOWHERE
#endif
#define CONFIG_ENV_SIZE 0x20000
#define PART_LAYOUT ""
/* Armbian: unmodified SDK output, kept as generated. The vendor raw
 * BOOT/MISC/ROOTFS layout below is not the layout of an Armbian card - that
 * is an MBR disk image with a FAT /boot and an ext4 root - and distroboot
 * reads none of it. Only the vendor fallback paths (sdboot, cvi_update) still
 * refer to these, so the values stay as the SDK emitted them.
 */
#define ROOTFS_DEV "/dev/mmcblk0p3"
#define PARTS_OFFSET \
"BOOT_PART_OFFSET=0x0\0" \
"BOOT_PART_SIZE=0x40000\0" \
"MISC_PART_OFFSET=0x40000\0" \
"MISC_PART_SIZE=0x1000\0" \
"ROOTFS_PART_OFFSET=0x41000\0" \
"ROOTFS_PART_SIZE=0x180100\0"
#define SPL_BOOT_PART_OFFSET 0x0
#endif