version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Ljubljana"
    open-pull-requests-limit: 3
    labels:
      - "GitHub Actions"
      - "Dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Ljubljana"
    open-pull-requests-limit: 3
    labels:
      - "GitHub Actions"
      - "Dependencies"
      - "Python"
