./compile.sh build BOARD=rg34xxsp BRANCH=current RELEASE=noble BUILD_MINIMAL=no BUILD_DESKTOP=yes DESKTOP_ENVIRONMENT="gnome" DESKTOP_APPGROUPS_SELECTED=""  DESKTOP_ENVIRONMENT_CONFIG_NAME="config_base" KERNEL_CONFIGURE=no
./compile.sh build BOARD=rg34xxsp BRANCH=current RELEASE=noble BUILD_MINIMAL=no BUILD_DESKTOP=yes DESKTOP_ENVIRONMENT="xfce" DESKTOP_APPGROUPS_SELECTED="" DESKTOP_ENVIRONMENT_CONFIG_NAME="config_base" KERNEL_CONFIGURE=no
./compile.sh build BOARD=rg34xxsp BRANCH=current RELEASE=bookworm BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_CONFIGURE=no
./compile.sh build BOARD=rg34xxsp BRANCH=current RELEASE=bookworm BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no
./compile.sh build BOARD=rg34xxsp BRANCH=current RELEASE=noble BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_CONFIGURE=no
./compile.sh build BOARD=rg34xxsp BRANCH=current RELEASE=noble BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no