#!/bin/sh

# Source based on: https://github.com/azlux/log2ram
# License: MIT
# License file: /usr/share/log2ram/LICENSE

SIZE=40M
USE_RSYNC=false
ENABLED=false
ME="${0##*/}"
DIRNAME="$(sed 's/2ram$//' <<<"${ME}")"

[ -f /etc/default/${ME} ] && . /etc/default/${ME}

[ "$ENABLED" != true ] && exit 0

# don't touch anything below here.

HDD_LOG=/var/${DIRNAME}.hdd/
RAM_LOG=/var/${DIRNAME}/
LOG2RAM_LOG="${HDD_LOG}${ME}.log"
LOG_OUTPUT="tee -a $LOG2RAM_LOG"

isSafe () {
    [ -d $HDD_LOG ] || echo "ERROR: $HDD_LOG doesn't exist!  Can't sync."
    [ -d $HDD_LOG ] || exit 1
}

syncToDisk () {
    isSafe

    if [ "$USE_RSYNC" = true ]; then
        rsync -aXWv --delete --exclude ${ME}.log --links $RAM_LOG $HDD_LOG 2>&1 | $LOG_OUTPUT
    else
        cp -rfup $RAM_LOG -T $HDD_LOG 2>&1 | $LOG_OUTPUT
    fi
}

syncFromDisk () {
    isSafe

    if [ "$USE_RSYNC" = true ]; then
        rsync -aXWv --delete --exclude ${ME}.log --links $HDD_LOG $RAM_LOG 2>&1 | $LOG_OUTPUT
    else
        cp -rfup $HDD_LOG -T $RAM_LOG 2>&1 | $LOG_OUTPUT
    fi
}


case "$1" in
  start)
      [ -d $HDD_LOG ] || mkdir $HDD_LOG
      rm -f $LOG2RAM_LOG
      mount --bind $RAM_LOG $HDD_LOG
      mount --make-private $HDD_LOG
      mount -t tmpfs -o nosuid,noexec,nodev,mode=0755,size=$SIZE ${ME} $RAM_LOG
      syncFromDisk
      ;;

  stop)
      syncToDisk
      umount -l $RAM_LOG
      umount -l $HDD_LOG
      ;;

  write)
      syncToDisk
      ;;
  *)
      echo "Usage: ${ME} {start|stop|write}" >&2
      exit 1
      ;;
esac
