ARMBIAN_PKG_PACKAGE="armbian-${BOARD}-utils"
ARMBIAN_PKG_SECTION=kernel
ARMBIAN_PKG_ARCH=${ARCH}
ARMBIAN_PKG_REPLACES="armbian-tools-${RELEASE,,}"
ARMBIAN_PKG_DESCRIPTION="Armbian utilities for ${BOARD_NAME}"