# Use case configuration for AYN SM8750
# Author: Teguh Sobirin <teguh@sobir.in>

SectionVerb {
	EnableSequence [
		cset "name='SECONDARY_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	Include.wcde.File "/codecs/wcd939x/DefaultEnableSeq.conf"

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	Value {
		PlaybackChannels 2
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones playback"

	Include.wcdhpe.File "/codecs/wcd939x/HeadphoneABEnableSeq.conf"
	Include.wcdhpd.File "/codecs/wcd939x/HeadphoneDisableSeq.conf"
	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	Value {
		PlaybackChannels 2
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},1"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "HP Digital"
		JackControl "Headphone Jack"
		JackHWMute "Speaker"
	}
}
