.TH DRI2TEST 1 "August 23, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dri2test \- simple program to test the dri2 support
.SH SYNOPSIS
.B dri2test
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBdri2test\fP is a simple program to test the dri2 support by creating a X11 window,
connecting to the dri2 interface, and calling a set of basic functions to validate the
dri2 support at the system.
.SH AUTHOR
dri2test was written by Rob Clark <rob@ti.com>.
.PP
This manual page was written by Ricardo Salveti de Araujo <ricardo.salveti@linaro.org>,
for the Debian project (and may be used by others).
