debian/standard/doc/doxy/html/*		usr/share/doc/ffmpeg/api
doc/examples/*.c					usr/share/doc/ffmpeg/examples
doc/examples/Makefile				usr/share/doc/ffmpeg/examples
doc/examples/README					usr/share/doc/ffmpeg/examples
debian/standard/doc/*.html			usr/share/doc/ffmpeg/manual
debian/standard/doc/style.min.css	usr/share/doc/ffmpeg/manual
doc/APIchanges						usr/share/doc/ffmpeg/developer-info
doc/*.txt							usr/share/doc/ffmpeg/developer-info
usr/share/man/man3
