.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH QT-FASTSTART 1 "May 10, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
qt-faststart \- utility for Quicktime files
.SH SYNOPSIS
.B qt-faststart
.br
.SH DESCRIPTION
\fBqt-faststart\fP is a utility that rearranges a Quicktime file such that the
moov atom is in front of the data, thus facilitating network streaming.
.SH OPTIONS
Options processed by the executable:
.TP
\fB\<infile.mov>\fR
The source Quicktime file.
.TP
\fB\<outfile.mov>\fR
The destination Quicktime file.
.SH AUTHOR
This manual page was written by Andres Mejia <mcitadel@gmail.com>
for the Debian GNU/Linux system, but may be used by others.
