#!/bin/bash
#

# create directories
mkdir -p ${upperdir}/boot/bin
mkdir -p ${upperdir}/usr/share/armbian/
mkdir -p ${upperdir}/etc/default
mkdir -p ${upperdir}/usr/network
mkdir -p ${upperdir}/etc/mpv
mkdir -p ${upperdir}/etc/profile.d

# add boot script and environment
bootscript_src=${BOOTSCRIPT%%:*}
bootscript_dst=${BOOTSCRIPT##*:}

cp $SRC/config/bootscripts/$bootscript_src ${upperdir}/usr/share/armbian/$bootscript_dst

if [[ -n $BOOTENV_FILE && -f $SRC/config/bootenv/$BOOTENV_FILE ]]; then
	cp $SRC/config/bootenv/$BOOTENV_FILE $upperdir/usr/share/armbian/armbianEnv.txt
fi

# add configuration for setting uboot environment from userspace with: fw_setenv fw_printenv
if [[ -n $UBOOT_FW_ENV ]]; then
	UBOOT_FW_ENV=($(tr ',' ' ' <<< "$UBOOT_FW_ENV"))
	mkdir -p $upperdir/etc
	echo "# Device to access      offset           env size" > $upperdir/etc/fw_env.config
	echo "/dev/mmcblk0	${UBOOT_FW_ENV[0]}	${UBOOT_FW_ENV[1]}" >> $upperdir/etc/fw_env.config
fi

# create armbian-release file
cat <<-EOF > $upperdir/etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=$BOARD
BOARD_NAME="$BOARD_NAME"
BOARDFAMILY=${BOARDFAMILY}
VERSION=$REVISION
LINUXFAMILY=$LINUXFAMILY
BRANCH=$BRANCH
ARCH=$ARCHITECTURE
IMAGE_TYPE=$IMAGE_TYPE
BOARD_TYPE=$BOARD_TYPE
INITRD_ARCH=$INITRD_ARCH
KERNEL_IMAGE_TYPE=$KERNEL_IMAGE_TYPE
EOF

# convert and add fex files
for i in $(ls -w1 $SRC/config/fex/*.fex | xargs -n1 basename); do
	fex2bin $SRC/config/fex/${i%*.fex}.fex ${upperdir}/boot/bin/${i%*.fex}.bin
done

# add some summary to the image
fingerprint_image "$upperdir/etc/armbian.txt"

# fixing permissions (basic), reference: dh_fixperms
find $upperdir -print0 2>/dev/null | xargs -0r chown --no-dereference 0:0
find $upperdir ! -type l -print0 2>/dev/null | xargs -0r chmod 'go=rX,u+rw,a-s'