#!/bin/bash
#
# adjust htop settings for all normal users and root
#

. /etc/armbian-release

for homedir in $(awk -F'[:]' '{if ($3 >= 1000 && $3 != 65534 || $3 == 0) print $6}' /etc/passwd); do

	unset FIELDS FIELD_PARA

	# start with a clean copy
	cp /etc/skel/.config/htop/htoprc "${homedir}"/.config/htop/htoprc

	for TYPE in ethernet wifi; do

		i=0
		for INTERFAC in $(LC_ALL=C nmcli device status | grep $TYPE | grep -w connected | awk '{ print $1 }' | grep -v lo | grep -v p2p | head -2); do

			[[ $TYPE == ethernet ]] && type="eth"; [[ $TYPE == wifi ]] && type="wlan"

			# offload tx if conditions are met
			[[ $TYPE == ethernet && $LINUXFAMILY == rockchip64 ]] && ethtool -K ${INTERFAC} tx off

			FIELDS+="${type^}$i ${type^}${i}stat "
			FIELD_PARA+="2 2 "
			sed -i "s/^${type}${i}_alias=.*/${type}${i}_alias=$INTERFAC/" "${homedir}"/.config/htop/htoprc

			((i=i+1))
		done
	done

	FIELDS=$(echo $FIELDS | xargs)
	FIELD_PARA=$(echo $FIELD_PARA | xargs)

	echo "$FIELDS $FIELD_PARA"

	sed -i "s/right_meters.*$/& $FIELDS/" "${homedir}"/.config/htop/htoprc
	sed -i "s/right_meter_modes.*$/& $FIELD_PARA/" "${homedir}"/.config/htop/htoprc

	# enable GPU where this works
	if [[ $LINUXFAMILY == meson64 || $LINUXFAMILY == odroidxu4 ]]; then
	        sed -i "s/left_meters.*$/& GpuTemp/" "${homedir}"/.config/htop/htoprc
        	sed -i "s/left_meter_modes.*$/& 2/" "${homedir}"/.config/htop/htoprc
	fi

done
