ARMBIAN_PKG_PACKAGE=armbian-${LINUXFAMILY}
ARMBIAN_PKG_SECTION=kernel
ARMBIAN_PKG_DEPENDS="mmc-utils"
ARMBIAN_PKG_SUGGESTS="armbian-firmware"
ARMBIAN_PKG_DESCRIPTION="Armbian support package for ${LINUXFAMILY}"