#!/bin/bash
export TERM=linux
export VDPAU_DRIVER=sunxi 
. /etc/os-release
KERNELID=$(uname -r) 
clear
toilet -f standard -F metal  $([ -f  /var/run/machine.id ] && cat /var/run/machine.id || cat /etc/hostname)
echo ""
printf 'Welcome to \e[0;91mARMBIAN\x1B[0m %s %s\n' "$PRETTY_NAME $KERNELID"
echo ""
