#!/bin/bash

NUM_UPDATES=0

[[ -f /var/cache/apt/archives/updates.number ]] && . /var/cache/apt/archives/updates.number

if [[ $NUM_UPDATES -gt 0 ]]; then
	echo -e "[\e[31m $NUM_SECURITY_UPDATES security updates available, $NUM_UPDATES updates total\e[0m: \e[1mapt upgrade\e[0m ]"
	echo -e "Last check: \e[92m$DATE\e[0m"
	echo
fi
