#!/bin/bash

THIS_SCRIPT="armbian-config"
MOTD_DISABLE=""

[[ -f /etc/default/armbian-motd ]] && . /etc/default/armbian-motd

for f in $MOTD_DISABLE; do
	[[ $f == $THIS_SCRIPT ]] && exit 0
done

echo -e "[\e[31m General system configuration\e[0m: \e[1marmbian-config\e[0m ]"
