#!/bin/bash

if [[ -f /var/run/reboot ]]; then
	printf "\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
	printf "\e[0;91mPlease reboot the system as soon as possible \x1B[0m \n\n"
	(sleep 1 && rm "$0") &
fi
