#!/bin/bash

if [[ -f /tmp/firstrun_running ]]; then
	printf "\n\e[0;91m Warning: firstrun script is running \x1B[0m \n"
	printf "\e[0;91m automatic reboot may be performed soon \x1B[0m \n"
fi

(sleep 1 && rm "$0") &
