#!/bin/bash

THIS_SCRIPT="point-to-faq"
MOTD_DISABLE=""

[[ -f /etc/default/armbian-motd ]] && . /etc/default/armbian-motd

for f in $MOTD_DISABLE; do
	[[ $f == $THIS_SCRIPT ]] && exit 0
done

. /etc/armbian-release

printf "New to Armbian? Check the documentation first: \e[0;92mhttps://docs.armbian.com\x1B[0m\n\n"

(sleep 1 && rm "$0") &