#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Main() {
	[[ -f /etc/armbian-release ]] && source /etc/armbian-release || read ID </run/machine.id
	case ${ID} in
		"Orange Pi+"*|"Orange Pi 2"*|"Orange Pi PC"*|"Orange Pi One"|"Orange Pi Lite"|"NanoPi M1"|"Beelink X2")
			echo -e "\nNew to Armbian? Check the Armbian H3 Mini FAQ first:\nhttps://github.com/igorpecovnik/lib/blob/master/documentation/H3_mini_faq.md\n\n"
			(sleep 1 && rm "$0") &
			;;
	esac
} # Main

Main
