Syntax 4

Comment "KICKPI K3B Sound"

SectionUseCase."HiFi" {
	File "/Rockchip/kickpi-k3b/kickpi-k3b-HiFi.conf"
	Comment "Play HiFi quality music"
}

BootSequence [
	cset "name='DAC Playback Volume' 252"
	cset "name='Playback Path' 'HP'"
]
