SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker"

	ConflictingDevice [
		"Headphones"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixerElem "DAC"
	}

	EnableSequence [
		cset "name='Playback Path' 'SPK'"
	]
}

SectionDevice."Headphones" {
	Comment "Headphones"

	ConflictingDevice [
		"Speaker"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixerElem "DAC"
		JackControl "Headphone Jack"
	}

	EnableSequence [
		cset "name='Playback Path' 'HP'"
	]
}
