# SPDX-License-Identifier: GPL-2.0
# TQ TQMa62xx/MBa62xx overlays
dtb-$(CONFIG_ARCH_K3) += k3-am62-tqma62xx-mba62xx-lvds-tm070jdhg30.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62-tqma62xx-mba62xx-lvds-vesa-fhd.dtbo
