/*
 *VO control GPIOs
 */
#define VO_GPIO_RESET_PORT		portb
#define VO_GPIO_RESET_INDEX		5
#define VO_GPIO_RESET_ACTIVE	GPIO_ACTIVE_LOW
#define VO_GPIO_PWM_PORT		portb
#define VO_GPIO_PWM_INDEX		4
#define VO_GPIO_PWM_ACTIVE		GPIO_ACTIVE_HIGH
#define VO_GPIO_POWER_CT_PORT	portb
#define VO_GPIO_POWER_CT_INDEX	3
#define VO_GPIO_POWER_CT_ACTIVE	GPIO_ACTIVE_HIGH

