#!/bin/sh

echo "START ddBR"

mkdir /home/public;chmod 777 /home/public

rm /home/public/arc_mmc

mkdir /home/public/arc_mmc;chmod 777 /home/public/arc_mmc

fdisk -l > /home/public/arc_mmc/fdisk_out_part.txt

dd if=/dev/mmcblk1 of=/home/public/arc_mmc/mmcblk1.img bs=1M conv=fsync

echo "STOP ddBR"
