[[ $BUILD_DESKTOP != yes && $DESKTOP_ENVIRONMENT != xfce ]] && ARMBIAN_PKG_INSTALL=no
ARMBIAN_PKG_PACKAGE=armbian-${RELEASE,,}-desktop-xfce
ARMBIAN_PKG_SECTION=xorg
ARMBIAN_PKG_REPOSITORY="${RELEASE,,}"
ARMBIAN_PKG_DEPENDS="${PACKAGE_LIST_DESKTOP}"
ARMBIAN_PKG_RECOMMENDS="${PACKAGE_LIST_DESKTOP_RECOMMENDS}"
ARMBIAN_PKG_PROVIDES="$ARMBIAN_PKG_PACKAGE"
ARMBIAN_PKG_REPLACES="armbian-${RELEASE,,}-desktop"
ARMBIAN_PKG_DESCRIPTION="Armbian XFCE desktop for ${DISTRIBUTION} ${RELEASE}"