#!/bin/bash
#
# Copyright (c) Authors: https://www.armbian.com/authors
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# DO NOT EDIT THIS FILE
# any changes will be lost on board support package update

if [[ -f /var/run/resize2fs-reboot ]]; then
	printf "\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
	printf "\e[0;91mPlease reboot the system as soon as possible \x1B[0m \n"
fi
