# SPDX-License-Identifier: GPL-2.0
# TQ TQMa9352 / MBa93xxLA-MINI / MBa93xxCA overlays
dtb-$(CONFIG_ARCH_MXC) += imx93-tqma9352-mba93xxla-mini-lvds-tm070jvhg33.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx93-tqma9352-mba93xxca-lvds-tm070jvhg33.dtbo
dtb-$(CONFIG_ARCH_MXC) += imx93-tqma9352-mba93xxca-fan.dtbo
