# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MACH_SUN4I) += \
	sun4i-a10-analog-codec.dtbo \
	sun4i-a10-can.dtbo \
	sun4i-a10-i2c1.dtbo \
	sun4i-a10-i2c2.dtbo \
	sun4i-a10-nand.dtbo \
	sun4i-a10-pps-gpio.dtbo \
	sun4i-a10-pwm.dtbo \
	sun4i-a10-spdif-out.dtbo \
	sun4i-a10-spi-jedec-nor.dtbo \
	sun4i-a10-spi-spidev.dtbo \
	sun4i-a10-uart2.dtbo \
	sun4i-a10-uart3.dtbo \
	sun4i-a10-uart4.dtbo \
	sun4i-a10-uart5.dtbo \
	sun4i-a10-uart6.dtbo \
	sun4i-a10-uart7.dtbo \
	sun4i-a10-w1-gpio.dtbo

dtb-$(CONFIG_MACH_SUN5I) += \
	sun5i-a13-analog-codec.dtbo \
	sun5i-a13-i2c1.dtbo \
	sun5i-a13-i2c2.dtbo \
	sun5i-a13-nand.dtbo \
	sun5i-a13-pwm.dtbo \
	sun5i-a13-spi0.dtbo \
	sun5i-a13-spi1.dtbo \
	sun5i-a13-spi2.dtbo \
	sun5i-a13-spi-jedec-nor.dtbo \
	sun5i-a13-spi-spidev.dtbo \
	sun5i-a13-uart0.dtbo \
	sun5i-a13-uart1.dtbo \
	sun5i-a13-uart2.dtbo \
	sun5i-a13-uart3.dtbo

dtb-$(CONFIG_MACH_SUN7I) += \
	sun7i-a20-analog-codec.dtbo \
	sun7i-a20-can.dtbo \
	sun7i-a20-i2c1.dtbo \
	sun7i-a20-i2c2.dtbo \
	sun7i-a20-i2c3.dtbo \
	sun7i-a20-i2c4.dtbo \
	sun7i-a20-mmc2.dtbo \
	sun7i-a20-nand.dtbo \
	sun7i-a20-pps-gpio.dtbo \
	sun7i-a20-pwm.dtbo \
	sun7i-a20-spdif-out.dtbo \
	sun7i-a20-spi-add-cs1.dtbo \
	sun7i-a20-spi-jedec-nor.dtbo \
	sun7i-a20-spi-spidev.dtbo \
	sun7i-a20-uart2.dtbo \
	sun7i-a20-uart3.dtbo \
	sun7i-a20-uart4.dtbo \
	sun7i-a20-uart5.dtbo \
	sun7i-a20-uart6.dtbo \
	sun7i-a20-uart7.dtbo \
	sun7i-a20-w1-gpio.dtbo

dtb-$(CONFIG_MACH_SUN8I) += \
	sun8i-h3-analog-codec.dtbo \
	sun8i-h3-cir.dtbo \
	sun8i-h3-cpu-clock-1.2GHz-1.3v.dtbo \
	sun8i-h3-cpu-clock-1.368GHz-1.3v.dtbo \
	sun8i-h3-cpu-clock-1.3GHz-1.3v.dtbo \
	sun8i-h3-i2c0.dtbo \
	sun8i-h3-i2c1.dtbo \
	sun8i-h3-i2c2.dtbo \
	sun8i-h3-pps-gpio.dtbo \
	sun8i-h3-pwm.dtbo \
	sun8i-h3-spdif-out.dtbo \
	sun8i-h3-spi-add-cs1.dtbo \
	sun8i-h3-spi-jedec-nor.dtbo \
	sun8i-h3-spi-spidev.dtbo \
	sun8i-h3-uart1.dtbo \
	sun8i-h3-uart2.dtbo \
	sun8i-h3-uart3.dtbo \
	sun8i-h3-usbhost0.dtbo \
	sun8i-h3-usbhost1.dtbo \
	sun8i-h3-usbhost2.dtbo \
	sun8i-h3-usbhost3.dtbo \
	sun8i-h3-w1-gpio.dtbo \
	sun8i-r40-i2c2.dtbo \
	sun8i-r40-i2c3.dtbo \
	sun8i-r40-spi-spidev0.dtbo \
	sun8i-r40-spi-spidev1.dtbo \
	sun8i-r40-uart2.dtbo \
	sun8i-r40-uart4.dtbo \
	sun8i-r40-uart5.dtbo \
	sun8i-r40-uart7.dtbo

scr-$(CONFIG_MACH_SUN4I) += sun4i-a10-fixup.scr
scr-$(CONFIG_MACH_SUN5I) += sun5i-a13-fixup.scr
scr-$(CONFIG_MACH_SUN7I) += sun7i-a20-fixup.scr
scr-$(CONFIG_MACH_SUN8I) += sun8i-h3-fixup.scr

dtbotxt-$(CONFIG_MACH_SUN4I) += README.sun4i-a10-overlays
dtbotxt-$(CONFIG_MACH_SUN5I) += README.sun5i-a13-overlays
dtbotxt-$(CONFIG_MACH_SUN7I) += README.sun7i-a20-overlays
dtbotxt-$(CONFIG_MACH_SUN8I) += README.sun8i-h3-overlays
