# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
	hinlink-h88k-240x135-lcd.dtbo \
	rk35xx-radxa-zero-3w-ext-ant.dtbo \
	rk3308-uart1.dtbo rk3308-uart2.dtbo rk3308-uart3.dtbo \
	rk3308-otg-host.dtbo \
	rk3308-s0-ext-antenna.dtbo \
	rk3308-b@1.3ghz.dtbo \
	rk3308-bs.dtbo rk3308-bs@1.3ghz.dtbo \
	rk3308-pcm5102a.dtbo \
	rockchip-dusun-010r-rp3328b.dtbo \
	rockchip-sakurapi-rk3308b-ws2812.dtbo \
	rockchip-rockpi4cplus-usb-host.dtbo \
	rockchip-rockpro64-lcd.dtbo \
	rockchip-rk3318-box-cpu-hs.dtbo \
	rockchip-rk3318-box-emmc-ddr.dtbo \
	rockchip-rk3318-box-emmc-hs200.dtbo \
	rockchip-rk3318-box-led-conf1.dtbo \
	rockchip-rk3318-box-led-conf2.dtbo \
	rockchip-rk3318-box-led-conf3.dtbo \
	rockchip-rk3318-box-led-conf4.dtbo \
	rockchip-rk3318-box-led-conf5.dtbo \
	rockchip-rk3318-box-led-conf6.dtbo \
	rockchip-rk3318-box-led-conf7.dtbo \
	rockchip-rk3318-box-wlan-ap6330.dtbo \
	rockchip-rk3318-box-wlan-ap6334.dtbo \
	rockchip-rk3318-box-wlan-ext.dtbo \
	rockchip-rk3328-i2c0.dtbo \
	rockchip-rk3328-i2s1-pcm5102.dtbo \
	rockchip-rk3328-mksklipad50-enable-rtc-end1.dtbo \
	rockchip-rk3328-mksklipad50-enable-v4l2.dtbo \
	rockchip-rk3328-mkspi-disable-lcd-spi.dtbo \
	rockchip-rk3328-opp-1.4ghz.dtbo \
	rockchip-rk3328-opp-1.5ghz.dtbo \
	rockchip-rk3328-spi-spidev.dtbo \
	rockchip-rk3328-uart1.dtbo \
	rockchip-rk3399-dwc3-0-host.dtbo \
	rockchip-rk3399-i2c7.dtbo \
	rockchip-rk3399-i2c8.dtbo \
	rockchip-rk3399-opp-2ghz.dtbo \
	rockchip-rk3399-pcie-gen2.dtbo \
	rockchip-rk3399-spi-jedec-nor.dtbo \
	rockchip-rk3399-spi-spidev.dtbo \
	rockchip-rk3399-uart4.dtbo \
	rockchip-rk3399-w1-gpio.dtbo \
	rockchip-rk3566-sata2.dtbo \
	rockchip-rk3568-nanopi-r5c-leds.dtbo \
	rockchip-rk3568-nanopi-r5s-leds.dtbo \
	rockchip-rk3568-hk-i2c0.dtbo \
	rockchip-rk3568-hk-i2c1.dtbo \
	rockchip-rk3568-hk-pwm1.dtbo \
	rockchip-rk3568-hk-pwm2.dtbo \
	rockchip-rk3568-hk-pwm9.dtbo \
	rockchip-rk3568-hk-spi-spidev.dtbo \
	rockchip-rk3568-hk-uart0.dtbo \
	rockchip-rk3568-hk-uart0-rts_cts.dtbo \
	rockchip-rk3568-hk-uart1.dtbo \
	rockchip-rk3568-rock-3a-disable-uart2.dtbo \
	rockchip-rk3588-fanctrl.dtbo \
	rockchip-rk3588-sata0.dtbo \
	rockchip-rk3588-sata1.dtbo \
	rockchip-rk3588-sata2.dtbo \
	rockchip-rk3588-hdmirx.dtbo \
	rockchip-rk3588-i2c8-m2.dtbo \
	rockchip-rk3588-pwm0-m0.dtbo \
	rockchip-rk3588-pwm0-m1.dtbo \
	rockchip-rk3588-pwm0-m2.dtbo \
	rockchip-rk3588-pwm1-m0.dtbo \
	rockchip-rk3588-pwm1-m1.dtbo \
	rockchip-rk3588-pwm1-m2.dtbo \
	rockchip-rk3588-pwm2-m1.dtbo \
	rockchip-rk3588-pwm3-m0.dtbo \
	rockchip-rk3588-pwm3-m1.dtbo \
	rockchip-rk3588-pwm3-m2.dtbo \
	rockchip-rk3588-pwm3-m3.dtbo \
	rockchip-rk3588-pwm5-m2.dtbo \
	rockchip-rk3588-pwm6-m0.dtbo \
	rockchip-rk3588-pwm6-m2.dtbo \
	rockchip-rk3588-pwm7-m0.dtbo \
	rockchip-rk3588-pwm7-m3.dtbo \
	rockchip-rk3588-pwm8-m0.dtbo \
	rockchip-rk3588-pwm10-m0.dtbo \
	rockchip-rk3588-pwm11-m0.dtbo \
	rockchip-rk3588-pwm11-m1.dtbo \
	rockchip-rk3588-pwm12-m0.dtbo \
	rockchip-rk3588-pwm13-m0.dtbo \
	rockchip-rk3588-pwm13-m2.dtbo \
	rockchip-rk3588-pwm14-m0.dtbo \
	rockchip-rk3588-pwm14-m1.dtbo \
	rockchip-rk3588-pwm14-m2.dtbo \
	rockchip-rk3588-pwm15-m0.dtbo \
	rockchip-rk3588-pwm15-m1.dtbo \
	rockchip-rk3588-pwm15-m2.dtbo \
	rockchip-rk3588-pwm15-m3.dtbo \
	rockchip-rk3588-uart1-m1.dtbo \
	rockchip-rk3588-uart3-m1.dtbo \
	rockchip-rk3588-uart4-m2.dtbo \
	rockchip-rk3588-uart6-m1.dtbo \
	rockchip-rk3588-uart7-m2.dtbo \
	rockchip-rk3588-uart8-m1.dtbo \
	rockchip-rk3588-rkvenc-overlay.dtbo \
	rockchip-rk3588-nanopi-m6-spi-nor-flash.dtbo \
	rockchip-rk3588-nanopi-m6-display-dsi1-yx35.dtbo \
	rockchip-rk3588-nanopc-t6-mmc-frequency.dtbo

scr-$(CONFIG_ARCH_ROCKCHIP) += \
       rockchip-fixup.scr

dtbotxt-$(CONFIG_ARCH_ROCKCHIP) += \
       README.rockchip-overlays

dtb-y += $(dtbo-y) $(scr-y) $(dtbotxt-y)

clean-files    := *.dtbo *.scr

