#!/usr/bin/bash

mkdir -p /boot/rauc

function get_rauc_device() {
    slot_with_idx=$1
    slot_device=$(cat /etc/rauc/system.conf | grep -PA3 "^\[slot.$slot_with_idx\]$" | grep -Po 'device=\K.*')
    if [ ! -z "${slot_device}" ]; then
        echo "Error: Could not find device for $slot_with_idx in rauc configuration"
    fi
    echo slot_device
}

case $1 in
    "get-primary")
        # Get the primary booted slot.
        if [ ! -z $(grep 'rootdev=UUID=' /boot/armbianEnv.txt) ]; then
            # Change to device name if UUID is being stored.
            current_dev=$(lsblk -plo name,mountpoint | grep -P '/$' | awk '{print $1;}')
            sed -i "/^rootdev=UUID=/crootdev=${current_dev}" /boot/armbianEnv.txt
        fi
        primary_device=$(grep -Po 'rootdev=\K.*' /boot/armbianEnv.txt)
        primary_label=$(blkid | grep $primary_device | grep -Po "PARTLABEL=\"\K[^\"]+")
        echo $primary_label
        ;;
    "set-primary")
        # Set the primary booted slot.
        target_label=$2
        target_device=$(lsblk -plo name,partlabel | grep $target_label | awk '{print $1;}')
	echo $target_device
        if [ -z "${target_device}" ]; then
            echo "Error: Target boot label \"$target_label\" not found"
            exit 1
        fi
        sed -i "/^rootdev=/crootdev=${target_device}" /boot/armbianEnv.txt
        ;;
    "get-state")
        # Get boot state for selected slot.
        target_label=$2
        if [ ! -f "/boot/rauc/$target_label-state" ]; then
            echo "good" > /boot/rauc/$target_label-state
        fi
        cat /boot/rauc/$target_label-state
        ;;
    "set-state")
        # Set boot state for selected slot.
        target_label=$2
        desired_state=$3
        echo $desired_state > /boot/rauc/$target_label-state
        ;;
    "get-current")
        # Get the currently booted slot.
        current_dev=$(lsblk -lo name,mountpoint | grep -P '/$' | awk '{print $1;}')
        current_label=$(blkid | grep -P "$current_dev: " | grep -Po 'PARTLABEL="\K[^"]+')
        echo $current_label
        ;;
esac

