#!/usr/bin/bash

# Import u-boot install tools
echo "Importing u-boot tools..."
source /usr/lib/u-boot/platform_install.sh

# Find root partition device
echo "Finding root partition..."
root_uuid=$(sed -e 's/^.*root=//' -e 's/ .*$//' < /proc/cmdline)
root_partition=$(blkid | tr -d '":' | grep "${root_uuid}" | awk '{print $1}')
root_partition_name=$(echo $root_partition | sed 's/\/dev\///g')
root_partition_device_name=$(lsblk -ndo pkname $root_partition)
root_partition_device=/dev/$root_partition_device_name

# Write u-boot platform
echo "Installing u-boot platform..."
write_uboot_platform "$DIR" "${root_partition_device}"

# Update boot script
echo "Updating boot configuration..."
if [ -f /boot/boot.cmd.new ]; then
	mv -f /boot/boot.cmd.new /boot/boot.cmd >/dev/null 2>&1
	mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr  >/dev/null 2>&1
elif [ -f /boot/boot.ini.new ]; then
	mv -f /boot/boot.ini.new /boot/boot.ini >/dev/null 2>&1
	rootdev=$(sed -e 's/^.*root=//' -e 's/ .*$//' < /proc/cmdline)
	rootfstype=$(sed -e 's/^.*rootfstype=//' -e 's/ .*$//' < /proc/cmdline)
	sed -i "s/setenv rootfstype.*/setenv rootfstype \"$rootfstype\"/" /boot/boot.ini
        sed -i "s/setenv rootdev.*/setenv rootdev \"$rootdev\"/" /boot/boot.ini
fi

echo "Done!"
