#!/usr/bin/env bash
echo "Running post-install"

# This gets run multiple times during the build process, so must be careful
# when the operations are actually performed!

# Remove these links as they produce warnings when the package is unpacked
if [ "$IMAGE_TOP" != "" ]; then
   if [ "$version" != "" ]; then
      rm -f $IMAGE_TOP/lib/modules/$version/build
      rm -f $IMAGE_TOP/lib/modules/$version/source
      mkimage -A arm -O linux -T kernel -C none -a 0x80008000 -e 0x80008000 -n "Linux kernel" -d $IMAGE_TOP/boot/vmlinuz* $IMAGE_TOP/boot/uImage 
   fi
fi
