# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv load_addr "0x44000000"
setenv kerneladdr "0x40800000"
setenv initrdaddr "0x42000000"
setenv ftdaddr "0x44000000"

# default values (configurable)

setenv rootdev "/dev/mmcblk1p1"
setenv rootfstype "ext4"
setenv console "both"

if load mmc ${mmcbootdev}:${mmcbootpart} ${load_addr} /boot/armbianEnv.txt || load mmc ${mmcbootdev}:${mmcbootpart} ${load_addr} armbianEnv.txt; then
        env import -t ${load_addr} ${filesize}
fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "${consoleargs} console=ttySAC2,115200n8"; fi

setenv bootargs "${consoleargs} root=${rootdev} rootfstype=${rootfstype} rootwait earlyprintk panic=10 consoleblank=0 enforcing=0 loglevel=${verbosity} ${extraargs}"

# Environment variables to be defined before load (in includes files uboot/.../exy*.h):
# platform dependent: boardname, fdtfile
# system dependent: mmcbootdev, mmcbootpart

load mmc ${mmcbootdev}:${mmcbootpart} ${kerneladdr} /boot/zImage || load mmc ${mmcbootdev}:${mmcbootpart} ${kerneladdr} zImage
load mmc ${mmcbootdev}:${mmcbootpart} ${initrdaddr} /boot/uInitrd || load mmc ${mmcbootdev}:${mmcbootpart} ${initrdaddr} uInitrd
load mmc ${mmcbootdev}:${mmcbootpart} ${ftdaddr} /boot/dtb/exynos5422-odroidxu4.dtb || load mmc ${mmcbootdev}:${mmcbootpart} ${ftdaddr} dtb/exynos5422-odroidxu4.dtb

bootz ${kerneladdr} ${initrdaddr} ${ftdaddr}

# Generate boot.scr:
# mkimage -c none -A arm -T script -d boot.cmd boot.scr