# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

# default values
setenv rootdev "/dev/mmcblk0p1"
setenv rootfstype "ext4"
setenv verbosity "1"
setenv board_model "pro"
setenv ethaddr "00:50:43:84:fb:2f"
setenv eth1addr "00:50:43:25:fb:84"
setenv eth2addr "00:50:43:84:25:2f"
setenv eth3addr "00:50:43:0d:19:18"

if ext4load mmc 0:1 ${loadaddr} /boot/armbianEnv.txt || ext4load mmc 0:1 ${loadaddr} armbianEnv.txt; then
	env import -t ${loadaddr} ${filesize}
fi

if test "${board_model}" = "base"; then
	setenv fdtfile "armada-388-clearfog-base.dtb"
else
	setenv fdtfile "armada-388-clearfog.dtb"
fi

setenv bootargs "selinux=0 cgroup_disable=memory scandelay root=${rootdev} rw rootfstype=${rootfstype} console=ttyS0,115200 loglevel=${verbosity} rootwait ${extraargs}"

ext4load mmc 0:1 ${fdt_addr} boot/dtb/${fdtfile} || ext4load mmc 0:1 ${fdt_addr} dtb/${fdtfile}
ext4load mmc 0:1 ${ramdisk_addr_r} boot/uInitrd || ext4load mmc 0:1 ${ramdisk_addr_r} uInitrd
ext4load mmc 0:1 ${kernel_addr_r} boot/zImage || ext4load mmc 0:1 ${kernel_addr_r} zImage

setenv fdt_high 0xffffffff
setenv initrd_high 0xffffffff

bootz ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
