# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

# We can't use `test -z` due to the bug: https://lists.denx.de/pipermail/u-boot/2005-August/011447.html
if test -n "${bootdev}"; test $? != 0; then
    echo '=============================================================='
    echo 'Please set "bootdev" before calling this script.'
    echo ''
    echo 'Boot from usb:'
    echo '  setenv bootdev "usb 0"'
    echo '  usb start'
    echo '  fatload ${bootdev} 0x20800000 boot.scr && autoscr 0x20800000'
    echo ''
    echo 'Boot from eMMC:'
    echo '  setenv bootdev "mmc 1"'
    echo '  fatload ${bootdev} 0x20800000 boot.scr && autoscr 0x20800000'
    echo '=============================================================='
    exit 22
fi

echo "Try to boot from ${bootdev}"

fatload ${bootdev} 0x20800000 /armbianEnv.txt && env import -t 0x20800000 ${filesize}

if test -n "${rootdev}"; test $? != 0; then
	echo 'Please set "rootdev" before calling this script'
	echo 'or set it in armbianEnv.txt.'
	exit 22
fi

test -n "${consoleargs}" || setenv consoleargs "console=ttyAML0,115200n8"

# Boot Arguments
setenv bootargs ""
setenv bootargs "${bootargs} root=${rootdev} rootwait rw"
setenv bootargs "${bootargs} ${consoleargs} no_console_suspend consoleblank=0"

# Booting
fatload ${bootdev} 0x20800000 /uImage || exit 1
fatload ${bootdev} 0x22000000 /uInitrd || exit 1
fatload ${bootdev} 0x21800000 /dtb/meson8b-onecloud.dtb || exit 1

bootm 0x20800000 0x22000000 0x21800000

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
