# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv load_addr "0x9000000"
setenv overlay_error "false"
setenv skip_fixups "false"
# default values
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "off"

test -n "${distro_bootpart}" || distro_bootpart=1

echo "Boot script loaded from ${devtype} ${devnum}:${distro_bootpart}"

if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}armbianEnv.txt; then
	load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}armbianEnv.txt
	env import -t ${load_addr} ${filesize}
fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS2,1500000 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

# get PARTUUID of first partition on SD/eMMC the boot script was loaded from
if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:${distro_bootpart} partuuid; fi

setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"; fi

load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image

load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536
# overlays that applied cleanly: a failed fdt apply leaves the working FDT
# unusable, so they are re-applied after the DTB has been reloaded
setenv applied_overlays ""
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		if fdt apply ${load_addr}; then
			setenv applied_overlays "${applied_overlays} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo"
		else
			echo "Could not apply kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo, reloading DT and re-applying the overlays that worked"
			setenv overlay_error "true"
			load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
			fdt addr ${fdt_addr_r}
			fdt resize 65536
			for applied_overlay in ${applied_overlays}; do
				if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${applied_overlay}; then
					fdt apply ${load_addr} || setenv overlay_error "true"
				fi
			done
		fi
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		if fdt apply ${load_addr}; then
			setenv applied_overlays "${applied_overlays} ${prefix}overlay-user/${overlay_file}.dtbo"
		else
			echo "Could not apply user provided DT overlay ${overlay_file}.dtbo, reloading DT and re-applying the overlays that worked"
			setenv overlay_error "true"
			load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
			fdt addr ${fdt_addr_r}
			fdt resize 65536
			for applied_overlay in ${applied_overlays}; do
				if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${applied_overlay}; then
					fdt apply ${load_addr} || setenv overlay_error "true"
				fi
			done
		fi
	fi
done
if test "${overlay_error}" = "true"; then
	if fdt addr ${fdt_addr_r}; then
		echo "Could not apply every DT overlay, keeping the ones that were applied"
		# nothing was kept: the DTB is untouched, so skip the fixups
		test -n "${applied_overlays}" || setenv skip_fixups "true"
	else
		echo "Error applying DT overlays, restoring original DT"
		load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
		setenv skip_fixups "true"
	fi
fi
# the kernel fixup script also implements the overlay arguments, so it must
# still run for the overlays that were kept when another one failed
if test "${skip_fixups}" != "true"; then
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr
		echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
		source ${load_addr}
	fi
fi
# the user fixup script is opaque, so it stays on the no-error path only
if test "${overlay_error}" = "false"; then
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fixup.scr
		echo "Applying user provided fixup script (fixup.scr)"
		source ${load_addr}
	fi
fi

echo "Trying 'kaslrseed' command... Info: 'Unknown command' can be safely ignored since 'kaslrseed' does not apply to all boards."
kaslrseed # @TODO: This gives an error (Unknown command ' kaslrseed ' - try 'help') on many devices since CONFIG_CMD_KASLRSEED is not enabled
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
