# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv verbosity "1"
setenv bootargs "console=ttyS0,115200n1 root=/dev/mmcblk0p1 rw rootfstype=ext4 rootwait coherent_pool=4M audit=0 {verbosity} ${extraargs}"
ext4load mmc 1:1 0x86000000 /boot/uInitrd
ext4load mmc 1:1 0x84000000 /boot/zImage-dtb
bootz 0x84000000 0x86000000
# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
