# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#
setenv root "/dev/mmcblk1p1"
setenv rootfs "ext4"
setenv verbosity "1"
setenv bootargs "initcall_debug console=ttyS2,115200n1 root=${root} rw rootfstype=${rootfs} rootwait audit=0 loglevel=${verbosity}"
ext4load mmc ${mmcnum}:${mmcpart} ${fdtaddr} ${mmcfdtfile}
ext4load mmc ${mmcnum}:${mmcpart} ${rdaddr} ${mmcinitrdfile}
ext4load mmc ${mmcnum}:${mmcpart} ${kernel_addr_r} ${mmckernfile}
echo "Booting ${mmckernfile} ${mmcinitrdfile} ${mmcfdtfile} from: mmc ${mmcnum}:${mmcpart} using bootargs=${bootargs}"
bootz ${kernel_addr_r} ${rdaddr} ${fdtaddr}
# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
