config:

  name: filogic-mt7986-6.18
  kind: kernel
  type: mainline
  branch: linux-6.18.y
  maintainers:
    - { github: SuperKali, name: SuperKali, email: hello@superkali.me }

  patches-to-git:
    do-not-commit-files:
      - "MAINTAINERS"
    do-not-commit-regexes:
      - "^arch/([a-zA-Z0-9]+)/boot/dts/([a-zA-Z0-9]+)/Makefile$"
