#! /bin/sh
### BEGIN INIT INFO
# Provides:          ap6212-bluetooth
# Required-Start:    $local_fs
# Required-Stop:
# X-Start-Before:    bluetooth
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Patch firmware for ap6212 adapter
# Description:       Patch firmware for ap6212 adapter
### END INIT INFO

# exit if bluetooth utils are not installed
[ -f "/bin/hciconfig" ] || exit 0

# copy firmware

if [ -f "/lib/firmware/ap6212/bcm43438a0.hcd" ] && [ ! -f /etc/firmware/ap6212/4343A0.hcd ]; then
        mkdir -p /etc/firmware/ap6212
        cp /lib/firmware/ap6212/bcm43438a0.hcd /etc/firmware/ap6212/4343A0.hcd
fi


. /lib/lsb/init-functions

do_start () {

if [ ! -z $(hciconfig | /bin/grep UART | /usr/bin/cut -d: -f1) ]
then
    echo "ap6212 BT device allready initialized"
    hcitool dev
 else
    # Start patching
        rfkill unblock all
        echo "0" > /sys/class/rfkill/rfkill0/state
        echo "1" > /sys/class/rfkill/rfkill0/state
        echo " " > /dev/ttyS1
        hciattach /dev/ttyS1 bcm43xx 115200
        hciconfig hci0 up
fi
}

case "$1" in
  start)
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  status)
        hcitool dev
        ;;
  *)
        echo "Usage: ap6212-bluetooth [start|stop|status]" >&2
        exit 3
        ;;
esac