#! /bin/sh
### BEGIN INIT INFO
# Provides:          bootsplash
# Required-Start:    
# Required-Stop:     glibc
# Default-Start:     S
# Default-Stop:
# Short-Description: Show this to console during boot
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
# display boot image
#fbi -vt 1 -noverbose -d /dev/fb0 /etc/bootsplash.png
case "$1" in
    start)
        echo "Booting Debian ..." >> /dev/tty0 
        ;;

    *)
        ## If no parameters are given, print which are avaiable.
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac
