#! /bin/sh

### BEGIN INIT INFO
# Provides:          resize2fs
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

set -e
device="/dev/"$(lsblk -idn -o NAME | grep mmc)
PARTITIONS=$(($(fdisk -l $device | grep $device | wc -l)-1))
device="/dev/"$(lsblk -idn -o NAME | grep mmc)"p"$PARTITIONS
N=/etc/init.d/resize2fs

case "$1" in
  start)
	echo "Resizing SD card file-system..." 
        /sbin/resize2fs $device 2>/dev/null
		update-rc.d -f resize2fs remove >/dev/null 2>&1
        ;;
   stop)
        echo "Resizing in next start"
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
