#! /bin/sh

### BEGIN INIT INFO
# Provides:          resize2fs
# Required-Start:    $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     S   
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

set -e

N=/etc/init.d/resize2fs

case "$1" in
  start)
	    /sbin/resize2fs /dev/mmcblk0p1 &&
		/sbin/insserv -r resize2fs &&
		rm $N
        ;;
  *)
        echo "Usage: $N {start}" >&2
        exit 1
        ;;
esac

exit 0
