ARMBIAN_PKG_PACKAGE=armbian-config
ARMBIAN_PKG_ARCH=all
ARMBIAN_PKG_SECTION=utils
ARMBIAN_PKG_PRIORITY=optional
ARMBIAN_PKG_DEPENDS="bash iperf3 psmisc curl bc expect dialog iptables resolvconf debconf-utils unzip build-essential html2text apt-transport-https html2text dirmngr software-properties-common"
ARMBIAN_PKG_RECOMMENDS=armbian-bsp
ARMBIAN_PKG_SUGGESTS="libpam-google-authenticator qrencode network-manager sunxi-tools"
ARMBIAN_PKG_HOMEPAGE=optional
ARMBIAN_PKG_DESCRIPTION="Armbian configuration utility"