{
 "title": "Ethereum Nodes Monitor v2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "single_dev",
    "label": "Single device nodes",
    "query": "SHOW TAG VALUES FROM \"status_node\" with Key= \"host\" "
   },
   {
    "name": "dual_dev",
    "label": "Dual device nodes",
    "query": "SHOW TAG VALUES FROM \"status_node\" with Key= \"host\" "
   },
   { "name": "dual_exec", "query": "${dual_dev}_exec" },
   { "name": "dual_consensus", "query": "${dual_dev}_consensus" }
  ]
 },
 "panels": [
  { "title": "Single Device Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "status_node",
     "query": "SELECT \"active_percent\" FROM \"status_node\" WHERE (\"host\"::tag =~ /^$|dev4$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load & temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "cpu_load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag =~ /^$dev5$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag =~ /^$dev5$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deg_C" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "download_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "alias": "upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "upload_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain",
     "select": [
      [
       { "params": [ "last_block" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Execution",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "status_exec",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "status_consensus",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "last_block" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center; height: 50px;\">\r\n    <a href=\"https://web3pi.io\" target=\"_blank\" style=\"display: flex; align-items: center; height: 100%;\">\r\n        <img src=\"/public/img/web3pi_logo.png\" alt=\"Web3Pi Logo\" style=\"max-height: 95%; cursor: pointer;\">\r\n    </a>\r\n</div>\r\n"
   }
  },
  {
   "title": "CPU load & temperature history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "cpu_usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "temp",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "deg_C" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Sync progress",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Sync status history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "status_node",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_bytes\") FROM \"mem\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Dual Device Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Exec dev CPU load",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution device CPU load history",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_exec",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_consensus",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Sync progress",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      },
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_1" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      },
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_2" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      },
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_3" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution device memory use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"used_bytes\") FROM \"mem\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution device disk use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Cons dev CPU load",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus device CPU load history",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    },
    {
     "title": "Latest block",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "last_block" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Chain head",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "chain",
       "select": [
        [
         { "params": [ "last_block" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus device memory use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"used_bytes\") FROM \"mem\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus device disk use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}