# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
	rockchip-rk3588-sata1.dtbo \
	rockchip-rk3588-sata2.dtbo \
	rockchip-rk3588-i2c8-m2.dtbo \
	rockchip-rk3588-pwm0-m0.dtbo \
	rockchip-rk3588-pwm0-m1.dtbo \
	rockchip-rk3588-pwm0-m2.dtbo \
	rockchip-rk3588-pwm1-m0.dtbo \
	rockchip-rk3588-pwm1-m1.dtbo \
	rockchip-rk3588-pwm1-m2.dtbo \
	rockchip-rk3588-pwm2-m1.dtbo \
	rockchip-rk3588-pwm3-m0.dtbo \
	rockchip-rk3588-pwm3-m1.dtbo \
	rockchip-rk3588-pwm3-m2.dtbo \
	rockchip-rk3588-pwm3-m3.dtbo \
	rockchip-rk3588-pwm5-m2.dtbo \
	rockchip-rk3588-pwm6-m0.dtbo \
	rockchip-rk3588-pwm6-m2.dtbo \
	rockchip-rk3588-pwm7-m0.dtbo \
	rockchip-rk3588-pwm7-m3.dtbo \
	rockchip-rk3588-pwm8-m0.dtbo \
	rockchip-rk3588-pwm10-m0.dtbo \
	rockchip-rk3588-pwm11-m0.dtbo \
	rockchip-rk3588-pwm11-m1.dtbo \
	rockchip-rk3588-pwm12-m0.dtbo \
	rockchip-rk3588-pwm13-m0.dtbo \
	rockchip-rk3588-pwm13-m2.dtbo \
	rockchip-rk3588-pwm14-m0.dtbo \
	rockchip-rk3588-pwm14-m1.dtbo \
	rockchip-rk3588-pwm14-m2.dtbo \
	rockchip-rk3588-pwm15-m0.dtbo \
	rockchip-rk3588-pwm15-m1.dtbo \
	rockchip-rk3588-pwm15-m2.dtbo \
	rockchip-rk3588-pwm15-m3.dtbo \
	rockchip-rk3588-uart1-m1.dtbo \
	rockchip-rk3588-uart3-m1.dtbo \
	rockchip-rk3588-uart4-m2.dtbo \
	rockchip-rk3588-uart6-m1.dtbo \
	rockchip-rk3588-uart7-m2.dtbo \
	rockchip-rk3588-uart8-m1.dtbo

dtb-y += $(dtbo-y)

clean-files    := *.dtbo
