#!/usr/bin/env bash
set -e

SRC="$(
	cd "$(dirname "$0")/../.."
	pwd -P
)"
echo "SRC: ${SRC}"

TARGET_SH="${SRC}/lib/library-functions.sh"

echo "Writing ${TARGET_SH}"

cat <<- AUTOGEN_INCLUDES_HEADER > "${TARGET_SH}"
	#!/usr/bin/env bash
	# This file is/was autogenerated by ${0}; don't modify manually

AUTOGEN_INCLUDES_HEADER

find lib/functions -type f -name \*.sh | while read -r path; do
	ref="$(echo -n "${path}" | sed -e 's/lib\///g')"
	cat <<- AUTOGEN_INCLUDES_EACH >> "${TARGET_SH}"
		set -e # no errors tolerated. set -e is invoked before each sourced file to make sure.
		### ${path}
		# shellcheck source=${ref}
		source "\${SRC}"/${path}

	AUTOGEN_INCLUDES_EACH
done

cat <<- AUTOGEN_INCLUDES_FOOTER >> "${TARGET_SH}"

	set -e # no errors tolerated. one last time for the win!
	# This file is/was autogenerated by ${0}; don't modify manually
AUTOGEN_INCLUDES_FOOTER

echo "done."
