# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
	rockchip-rk3588-sata1.dtbo \
	rockchip-rk3588-sata2.dtbo

targets += $(dtbo-y)

always         := $(dtbo-y)
clean-files    := *.dtbo

