#!/bin/bash

# create directories
mkdir -p ${upperdir}/usr/share/armbian/ ${upperdir}/etc/default ${upperdir}/usr/network ${upperdir}/etc/mpv ${upperdir}/etc/profile.d

bootscript_src=${BOOTSCRIPT%%:*}
bootscript_dst=${BOOTSCRIPT##*:}

cp $SRC/config/bootscripts/$bootscript_src ${upperdir}/usr/share/armbian/$bootscript_dst

if [[ -n $BOOTENV_FILE && -f $SRC/config/bootenv/$BOOTENV_FILE ]]; then
	cp $SRC/config/bootenv/$BOOTENV_FILE $upperdir/usr/share/armbian/armbianEnv.txt
fi

# add configuration for setting uboot environment from userspace with: fw_setenv fw_printenv
if [[ -n $UBOOT_FW_ENV ]]; then
	UBOOT_FW_ENV=($(tr ',' ' ' <<< "$UBOOT_FW_ENV"))
	mkdir -p $upperdir/etc
	echo "# Device to access      offset           env size" > $upperdir/etc/fw_env.config
	echo "/dev/mmcblk0	${UBOOT_FW_ENV[0]}	${UBOOT_FW_ENV[1]}" >> $upperdir/etc/fw_env.config
fi

# armhwinfo, firstrun, armbianmonitor, etc. config file
cat <<-EOF > $upperdir/etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=$BOARD
BOARD_NAME="$BOARD_NAME"
BOARDFAMILY=${BOARDFAMILY}
VERSION=$REVISION
LINUXFAMILY=$LINUXFAMILY
BRANCH=$BRANCH
ARCH=$ARCHITECTURE
IMAGE_TYPE=$IMAGE_TYPE
BOARD_TYPE=$BOARD_TYPE
INITRD_ARCH=$INITRD_ARCH
KERNEL_IMAGE_TYPE=$KERNEL_IMAGE_TYPE
EOF


# this is required for NFS boot to prevent deconfiguring the network on shutdown
[[ $RELEASE == xenial || $RELEASE == stretch || $RELEASE == bionic ]] && [[ -f $upperdir/etc/network/interfaces.default ]] && \
sed -i 's/#no-auto-down/no-auto-down/g' $upperdir/etc/network/interfaces.default

if [[ ( $LINUXFAMILY == sun*i || $LINUXFAMILY == pine64 ) && $BRANCH == default ]]; then
	# add mpv config for vdpau_sunxi
	ln -fs mpv_sunxi_legacy.conf ${upperdir}/etc/mpv/mpv.conf
	echo "export VDPAU_OSD=1" > ${upperdir}/etc/profile.d/90-vdpau.sh
	chmod 755 ${upperdir/}/etc/profile.d/90-vdpau.sh
fi
#else
#if [[ $LINUXFAMILY == sunxi* && $BRANCH != default ]]; then
	# add mpv config for x11 output - slow, but it works compared to no config at all
	# TODO: Test which output driver is better with DRM
	ln -fs mpv_sunxi_mainline.conf ${upperdir}/etc/mpv/mpv.conf
#fi

# execute $LINUXFAMILY-specific tweaks
#	[[ $(type -t family_tweaks_bsp) == function ]] && family_tweaks_bsp

# add some summary to the image
fingerprint_image "$upperdir/etc/armbian.txt"

# fixing permissions (basic), reference: dh_fixperms
find $upperdir -print0 2>/dev/null | xargs -0r chown --no-dereference 0:0
find $upperdir ! -type l -print0 2>/dev/null | xargs -0r chmod 'go=rX,u+rw,a-s'
