# Altera Agilex 5 E-Series SoC FPGA Development Kit, dual A55 + dual A76, SD + QSPI
BOARD_NAME="Agilex 5 SoCDK"
BOARD_VENDOR="altera"
BOARDFAMILY="agilex5"
BOARD_MAINTAINER="dinguyen702"
INTRODUCED="2024"
BOOTCONFIG="socfpga_agilex5_defconfig"
BOOTFS_TYPE="fat"
BOOT_FDT_FILE="intel/socfpga_agilex5_socdk.dtb"
DEFAULT_CONSOLE="serial"
HAS_VIDEO_OUTPUT="no"
KERNEL_TARGET="current"
KERNEL_TEST_TARGET="current"
SERIALCON="ttyS0:115200"
