# Allwinner R40 quad core 2Gb SoC Wifi eMMC
BOARD_NAME="Banana Pi M2 Ultra"
BOARD_VENDOR="sinovoip"
BOARDFAMILY="sun8i"
BOARD_MAINTAINER=""
INTRODUCED="2016"
BOOTCONFIG="Bananapi_M2_Ultra_defconfig"
OVERLAY_PREFIX="sun8i-r40"
KERNEL_TARGET="current,edge,legacy"
KERNEL_TEST_TARGET="current"
