# Mediatek MT7623n quad core 2GB mPci 2xSATA 2xUSB3.0 5xGBE
BOARD_NAME="Banana Pi R2"
BOARDFAMILY="mt7623"
BOARD_MAINTAINER=""
BOOTCONFIG="mt7623n_bpir2_defconfig"
HAS_VIDEO_OUTPUT="no"
KERNEL_TARGET="legacy"
