# Allwinner H2+ quad core 512MB SoC Wi-Fi/BT
BOARD_NAME="Banana Pi M2 Zero"
BOARDFAMILY="sun8i"
BOARD_MAINTAINER="mhawkins-consultant"
BOOTCONFIG="bananapi_m2_zero_defconfig"
MODULES_LEGACY="g_serial"
MODULES_CURRENT="g_serial"
SERIALCON="ttyS0,ttyGS0"
KERNEL_TARGET="legacy,current,edge"
KERNEL_TEST_TARGET="current"
