# A83T octa core 2Gb SoC Wifi
BOARD_NAME="Banana Pi M3"
BOARDFAMILY="sun8i"
CPUMAX=1610000
BOOTCONFIG="Sinovoip_BPI_M3_defconfig"
MODULES=""
MODULES_NEXT=""
OVERLAY_PREFIX="sun8i-a83t"
#
KERNEL_TARGET="dev"
CLI_TARGET="stretch:dev"
DESKTOP_TARGET="stretch:dev"
#
CLI_BETA_TARGET=""
