# BeagleY-AI Texas Instruments AM67A quad core 4GB DDR4 USB3  4TOPS

BOARD_NAME="BeagleY-AI"
BOARD_VENDOR="beagleboard"
BOARDFAMILY="k3-beagle"
BOARD_MAINTAINER="Grippy98"
INTRODUCED="2024"
BOOT_SOC="j722s"
BOOTCONFIG="am67a_beagley_ai_a53_defconfig"
BOOTFS_TYPE="fat"
BOOT_FDT_FILE="k3-am67a-beagley-ai.dts"
PACKAGE_LIST_BOARD="v4l-utils gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad libgles2"
TIBOOT3_BOOTCONFIG="am67a_beagley_ai_r5_defconfig"
TIBOOT3_FILE="tiboot3-j722s-hs-fs-evm.bin"
DEFAULT_CONSOLE="serial"
KERNEL_TARGET="vendor,vendor-rt,edge"
KERNEL_TEST_TARGET="vendor"
SERIALCON="ttyS2"
ATF_PLAT="k3"
ATF_BOARD="lite"
OPTEE_ARGS=""
OPTEE_PLATFORM="k3-am62x"
CC33XX_SUPPORT="yes"
# TI Rogue driver builds J722S with the AM62P GPU system.
TI_DEBPKGS_FALLBACK_SUITES=("noble" "jammy")
TI_PACKAGES+=(
	"ti-img-rogue-driver-am62p-dkms"
	"ti-img-rogue-umlibs-am62p"
	"ti-img-rogue-tools-am62p"
	"ti-img-rogue-firmware-am62p"
	"gstreamer1.0-tools"
	"gstreamer1.0-plugins-good"
	"gstreamer1.0-plugins-bad"
	"gstreamer1.0-plugins-base"
)
if [[ "${RELEASE}" == "bookworm" || "${RELEASE}" == "jammy" ]]; then
	TI_PACKAGES+=("mesa-vulkan-drivers" "libgl1-mesa-dri")
fi
