# Allwinner H616 quad core 512MB/1GB RAM SoC WiFi
BOARD_NAME="BigTreeTech CB1"
BOARDFAMILY="sun50iw9"
BOARD_MAINTAINER="JohnTheCoolingFan"
BOOTCONFIG="bigtreetech_cb1_defconfig"
SERIALCON="ttyS0"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
FORCE_BOOTSCRIPT_UPDATE="yes"
BOOTFS_TYPE="fat"
BOOT_FS_LABEL="BOOT"
OVERLAY_PREFIX="sun50i-h616"
BOOT_FDT_FILE="allwinner/sun50i-h616-bigtreetech-cb1-sd.dtb"
