# Cix CD8180/CD8160 SoC 12 core 8-64GB RAM PCIe 4.0
BOARD_NAME="Cix-ACPI"
BOARD_VENDOR="cixtech"
BOARDFAMILY="cix-p1"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOARD_MAINTAINER="HeyMeco"
INTRODUCED="2025"
