# RK3399 hexa core 4GB SoC eMMC GBE USB3 WiFi
BOARD_NAME="Firefly RK3399"
BOARDFAMILY="rk3399"
BOOTCONFIG="firefly-rk3399_defconfig"
MODULES=""
MODULES_NEXT=""
KERNEL_TARGET="default,dev"
FULL_DESKTOP="yes"
