# NXP LS1046A quad core Cortex-A72 8GB RAM SoC eMMC GBE SFP+
BOARD_NAME="Mono Gateway Development Kit"
BOARD_VENDOR="mono"
BOARDFAMILY="ls1046a"
BOARD_MAINTAINER="tomazzaman"
BOOTCONFIG="mono_gateway_dk_defconfig"
KERNEL_TARGET="current"
SERIALCON="ttyS0"
BOOT_FDT_FILE="freescale/mono-gateway-dk.dtb"
BOOTENV_FILE="ls1046a.txt"
