# Rockchip RK3568 quad core 1-8GB SoC 2x2.5GBe eMMC USB3 SATA
BOARD_NAME="Hinlink HNAS"
BOARDFAMILY="rk35xx"
BOOTCONFIG="radxa-e25-rk3568_defconfig"
KERNEL_TARGET="legacy,vendor"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3568-hinlink-hnas.dtb"
BOOT_SCENARIO="spl-blobs"
WIREGUARD="no"
IMAGE_PARTITION_TABLE="gpt"
BOOTFS_TYPE="fat"
