# SpacemiT K3 16-core 60 TOPS of AI performance 10GbE networking
BOARD_NAME="SpacemiT K3 Pico-ITX"
BOARDFAMILY="spacemit-k3"
BOARD_MAINTAINER="pyavitz"
INTRODUCED="2026"
BOARD_VENDOR="spacemit"
KERNEL_TARGET="legacy"
BOOT_FDT_FILE="spacemit/k3-pico-itx.dtb"
SRC_EXTLINUX="yes"
SRC_CMDLINE="earlycon=sbi console=tty1 console=ttyS0,115200 loglevel=1"
PACKAGE_LIST_BOARD="rfkill bluetooth bluez bluez-tools"
KERNEL_TEST_TARGET="legacy"

function post_config_uboot_target__pico_itx() {
	declare -g UBOOT_LOGLEVEL="1"
	write_uboot_platform() {
		echo -e "NOTE: U-Boot needs to be flashed via fastboot to SPI."
	}
}

function post_family_tweaks_bsp__spacemit_k3() {
	pre_prepare_partitions() {
		declare -g OFFSET="1" # 2048
		declare -g IMAGE_PARTITION_TABLE="gpt"
	}
}
