# Rockchip RK3562 DDR3 eMMC GBE SWT6621S WLAN/BT
BOARD_NAME="KICKPI K3B"
BOARD_VENDOR="kickpi"
BOARDFAMILY="rk35xx"
BOARD_MAINTAINER="retro98boy"
INTRODUCED="2026"
KERNEL_TARGET="edge"
KERNEL_TEST_TARGET="edge"
MODULES_EDGE="panel-rocknix-generic-dsi"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3562-kickpi-k3b.dtb"
BOOT_SCENARIO="binman"
BOOT_SOC="rk3562"
IMAGE_PARTITION_TABLE="gpt"
PACKAGE_LIST_BOARD="alsa-ucm-conf"

function post_family_config__kickpi-k3b() {
	declare -g BOOTSCRIPT='boot-rockchip64-ttyS0.cmd:boot.cmd'
	declare -g OVERLAY_PREFIX="rk3562-kickpi-k3b"
	declare -g DEFAULT_OVERLAYS="demo-dsi-panel"

	display_alert "$BOARD" "mainline u-boot overrides" "info"

	declare -g BOOTCONFIG="kickpi-k3b-rk3562_defconfig"
	declare -g BOOTDELAY=1
	declare -g BOOTSOURCE="https://github.com/u-boot/u-boot.git"
	declare -g BOOTBRANCH="tag:v2026.07"
	declare -g BOOTPATCHDIR="v2026.07"
	declare -g BOOTDIR="u-boot-${BOARD}"
}
