# S905x quad core 2Gb RAM SoC eMMC
BOARD_NAME="Khadas VIM1"
BOARDFAMILY="meson64"
BOOTCONFIG="khadas-vim_defconfig"
#
MODULES=""
MODULES_NEXT=""
#
KERNEL_TARGET="dev"
CLI_TARGET="buster:dev"
DESKTOP_TARGET="buster:dev"
#
CLI_BETA_TARGET=""
DESKTOP_BETA_TARGET=""
