# Amlogic S805x quad core 1Gb RAM SoC eMMC
BOARD_NAME="La Frite"
BOARDFAMILY="meson-gxl"
BOARD_MAINTAINER="Tonymac32"
BOOTCONFIG="libretech-ac_defconfig"
BOOT_FDT_FILE="amlogic/meson-gxl-s805x-libretech-ac.dtb"
KERNEL_TARGET="current,edge"
FULL_DESKTOP="yes"
ASOUND_STATE="asound.state.mesongx"
BOOT_LOGO="desktop"
