# Rockchip RK3399 hexa core 4GB RAM SOC 16GB eMMC 2x USB2 1x USB3 1x USB-C HDMI 1x GbE WiFi/BT
BOARD_NAME="Lenovo Leez P710"
BOARDFAMILY="rockchip64"
BOARD_MAINTAINER="andyshrk"
BOOTCONFIG="leez-rk3399_defconfig"
BOOT_FDT_FILE="rockchip/rk3399-leez-p710.dtb"
BOOT_LOGO="desktop"
BOOT_SCENARIO="blobless"
FULL_DESKTOP="yes"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
