# Avnet MaaXBoard 8ULP (i.MX8ULP A2)
BOARD_NAME="Avnet MaaXBoard 8ULP"
BOARD_VENDOR="avnet"
BOARDFAMILY="imx8ulp"
BOARD_MAINTAINER="govindsi"
INTRODUCED="2023"
HAS_VIDEO_OUTPUT="yes"
ATF_PLAT="imx8ulp"
BOOTCONFIG="maaxboard-8ulp_defconfig"
KERNEL_TARGET="current"
KERNEL_TEST_TARGET="current"
DEFAULT_CONSOLE="serial"
SERIALCON="ttyLP1"
BOOT_FDT_FILE="freescale/maaxboard-8ulp.dtb"
