# MBa8MPxL with TQMa8MPxL
BOARD_NAME="MBa8MPxL"
BOARD_VENDOR="tqgroup"
BOARDFAMILY="imx8m"
BOARD_MAINTAINER="schmiedelm"
INTRODUCED="2024"
HAS_VIDEO_OUTPUT="yes"
ATF_PLAT="imx8mp"
ATF_UART_BASE="0x30a60000"
BOOTCONFIG="tqma8mpxl_multi_mba8mpxl_defconfig"
KERNEL_TARGET="current,edge"
DEFAULT_CONSOLE="serial"
SERIALCON="ttymxc3"
BOOT_FDT_FILE="freescale/imx8mp-tqma8mpql-mba8mpxl.dtb"
OVERLAY_PREFIX="imx8mp-tqma8mpql-mba8mpxl"
ASOUND_STATE="asound.state.tqma"
