# Rockchip RK3588 SoC octa core 4-16GB SoC 1GBe eMMC USB3 SATA WiFi/BT
declare -g BOARD_NAME="Mekotronics R58S2"
declare -g BOARD_VENDOR="mekotronics"
declare -g BOARDFAMILY="rockchip-rk3588"
declare -g BOARD_MAINTAINER="HeyMeco"
declare -g BOOTCONFIG="mekotronics_r58s2-rk3588_defconfig"
declare -g KERNEL_TARGET="vendor"
declare -g FULL_DESKTOP="yes"
declare -g BOOT_LOGO="desktop"
declare -g BOOT_FDT_FILE="rockchip/rk3588s-blueberry-r58s2.dtb"
declare -g BOOT_SCENARIO="spl-blobs"
declare -g BOOT_SOC="rk3588"
declare -g IMAGE_PARTITION_TABLE="gpt"
declare -g DISPLAY_MANAGER="wayland"
declare -g ASOUND_STATE="asound.state.rk3588hd"

# Enable bcmdhd extension for AP6256 via SDIO
enable_extension "bcmdhd"
BCMDHD_TYPE="sdio"

declare -g BLUETOOTH_HCIATTACH_PARAMS="-s 115200 /dev/ttyS9 bcm43xx 115200 noflow nosleep"
enable_extension "bluetooth-hciattach"

#function pre_install_kernel_debs__extra_boot_args() {
#	display_alert "$BOARD" "Add extraboardargs for bcmdhd" "info"
#	run_host_command_logged echo "extraboardargs=bcmdhd.firmware_path=/lib/firmware/fw_bcm43455c0_ag.bin bcmdhd.nvram_path=/lib/firmware/nvram_ap6256.txt" >> "${SDCARD}"/boot/armbianEnv.txt
#
#	return 0
#}

function post_family_tweaks__mekotronics_r58s2_naming_audios() {
	display_alert "$BOARD" "Renaming r58s2 audios" "info"

	mkdir -p "${SDCARD}/etc/udev/rules.d/"
	echo 'SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-hdmi0-sound", ENV{SOUND_DESCRIPTION}="HDMI0 Audio"' > "${SDCARD}/etc/udev/rules.d/90-naming-audios.rules"
	echo 'SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-es8316-sound", ENV{SOUND_DESCRIPTION}="ES8316 Audio"' >> "${SDCARD}/etc/udev/rules.d/90-naming-audios.rules"

	return 0
}
