# SpacemiT M1 octa core RISC-V SoC 8GB/16GB RAM 2x USB3
BOARD_NAME="SpacemiT MUSE Book"
BOARDFAMILY="spacemit"
BOARD_MAINTAINER="pyavitz"
INTRODUCED="2024"
BOARD_VENDOR="spacemit"
KERNEL_TARGET="legacy"
BOOT_FDT_FILE="spacemit/k1-musebook.dtb"
BOOTDELAY=1
PACKAGE_LIST_BOARD="rfkill bluetooth bluez bluez-tools"
MODULES_BLACKLIST="rtw89_8852be"
SRC_EXTLINUX="yes"
SRC_CMDLINE="console=ttyS0,115200 console=tty1 loglevel=1 plymouth.prefer-fbcon clk_ignore_unused"

function post_config_uboot_target__extra_configs_for_musepi_pro() {
	display_alert "u-boot for ${BOARD}" "u-boot: enabling extra configs" "info"
	run_host_command_logged scripts/config --enable CONFIG_SD_BOOT
	run_host_command_logged scripts/config --enable CONFIG_EXT4_WRITE
	run_host_command_logged scripts/config --enable CONFIG_FS_BTRFS
	run_host_command_logged scripts/config --enable CONFIG_CMD_BTRFS
	run_host_command_logged scripts/config --enable CONFIG_SPI_FLASH_USE_4K_SECTORS
	declare -g UBOOT_LOGLEVEL="1"
}

function post_family_tweaks_bsp__musebook_extras() {
	if [[ -d "$SRC/packages/blobs/riscv64/spacemit" ]]; then
		run_host_command_logged mkdir -pv "${destination}"/lib/firmware
		display_alert "$BOARD" "Installing boot firmware" "info"
		run_host_command_logged cp -fv $SRC/packages/blobs/riscv64/spacemit/esos.elf "${destination}"/lib/firmware
	fi
	display_alert "$BOARD" "Force load wireless" "info"
	run_host_command_logged mkdir -pv "${destination}"/etc/modules-load.d
	run_host_command_logged echo "8852bs" > "${destination}"/etc/modules-load.d/${BOARD}.conf
	display_alert "$BOARD" "Set 8852be log levels" "info"
	run_host_command_logged mkdir -pv "${destination}"/etc/modprobe.d
	run_host_command_logged echo "options 8852be rtw_drv_log_level=0 rtw_phl_log_level=0" > "${destination}"/etc/modprobe.d/${BOARD}.conf
}
