# Rockchip RK3588 octa core 8-32GB RAM SoC 32-256GB eMMC USB3 USB2 2x 2.5GbE
source "${SRC}/config/boards/nanopct6.conf"
BOARD_NAME="NanoPC T6 LTS Plus"
BOARD_VENDOR="friendlyelec"
# Important: despite sourcing the nanopct6 file above, this file still has to contain some variables, due the way Armbian's JSON matrix generator works.
BOARDFAMILY="rockchip-rk3588"
BOARD_MAINTAINER="igorpecovnik"
BOOT_FDT_FILE="rockchip/rk3588-nanopc-t6-lts-plus.dtb"
KERNEL_TARGET="current,edge,vendor"
KERNEL_TEST_TARGET="vendor,current"
declare -g GRUB_FDT_FILE="${BOOT_FDT_FILE}" # u-boot autodetects, but grub needs to know; store it here so we can unset later

# Override: u-boot can't auto-detect the LTS Plus variant, so keep BOOT_FDT_FILE set
function post_family_config__t6_and_t6_lts_auto_dtb_name_via_uboot_detection() {
	:
}

function post_family_tweaks__nanopct6_lts_plus_naming_audios() {
	display_alert "$BOARD" "Renaming nanopct6-lts-plus audio" "info"

	mkdir -p $SDCARD/etc/udev/rules.d/
	echo 'SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-hdmi0-sound", ENV{SOUND_DESCRIPTION}="HDMI0 Audio"' > $SDCARD/etc/udev/rules.d/90-naming-audios.rules
	echo 'SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-hdmi1-sound", ENV{SOUND_DESCRIPTION}="HDMI1 Audio"' >> $SDCARD/etc/udev/rules.d/90-naming-audios.rules
	echo 'SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-hdmiin-sound", ENV{SOUND_DESCRIPTION}="HDMI-In Audio"' >> $SDCARD/etc/udev/rules.d/90-naming-audios.rules
	echo 'SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-dp0-sound", ENV{SOUND_DESCRIPTION}="DP0 Audio"' >> $SDCARD/etc/udev/rules.d/90-naming-audios.rules
	echo 'SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-es8389-sound", ENV{SOUND_DESCRIPTION}="ES8389 Audio"' >> $SDCARD/etc/udev/rules.d/90-naming-audios.rules

	return 0
}
