# Rockchip RK3588S octa core 8GB RAM SoC eMMC USB3 USB2 1x GbE 1x M2-E 1x M2-M
source "${SRC}/config/boards/friendlyelec-rk3588.conf"

BOARD_NAME="NanoPi M6"
BOARD_VENDOR="friendlyelec"
BOARD_MAINTAINER="efectn"
INTRODUCED="2023"
# These are repeated because the JSON matrix generator parses this file directly.
BOARDFAMILY="rockchip-rk3588"
KERNEL_TARGET="current,edge,vendor"
KERNEL_TEST_TARGET="vendor,current"
