# Nexell S5P6818 octa core 1GB RAM SoC GBE eMMC/SD
BOARD_NAME="NanoPi Fire3"
BOARDFAMILY="s5p6818"
BOARD_MAINTAINER="igorpecovnik"
BOOTCONFIG="s5p6818_nanopim3_defconfig"
MODULES_CURRENT="g_serial"
SERIALCON="ttySAC0,ttyGS0"
KERNEL_TARGET="current"
