# Allwinner H2+ quad core 256/512MB RAM SoC headless WiFi
BOARD_NAME="NanoPi Duo"
BOARDFAMILY="sun8i"
BOOTCONFIG="nanopi_duo_defconfig"
MODULES="g_serial"
MODULES_BLACKLIST="lima"
DEFAULT_OVERLAYS="usbhost2 usbhost3"
DEFAULT_CONSOLE="serial"
HAS_VIDEO_OUTPUT="no"
SERIALCON="ttyS0,ttyGS0"
KERNEL_TARGET="current,edge"
