# Allwinner H5 quad core 2GB RAM Wifi GBE eMMC
BOARD_NAME="NanoPi K1 Plus"
BOARD_VENDOR="friendlyelec"
BOARDFAMILY="sun50iw2"
BOARD_MAINTAINER=""
BOOTCONFIG="nanopi_k1_plus_defconfig"
DEFAULT_OVERLAYS="analog-codec"
KERNEL_TARGET="current,edge,legacy"
KERNEL_TEST_TARGET="current"
CRUSTCONFIG="h5_defconfig"
