# Allwinner H3 quad core 512MB RAM SoC headless WiFi/BT
BOARD_NAME="NanoPi Duo2"
BOARDFAMILY="sun8i"
BOOTCONFIG="nanopi_duo2_defconfig"
MODULES="g_serial"
MODULES_BLACKLIST="lima"
DEFAULT_OVERLAYS="usbhost0 usbhost2 usbhost3"
DEFAULT_CONSOLE="serial"
HAS_VIDEO_OUTPUT="no"
SERIALCON="ttyS0,ttyGS0"
KERNEL_TARGET="current,edge"
