# Allwinner A13 ARM Cortex-A8 1GHz with 256MB or 512MB RAM
BOARD_NAME="Olimex A13-SOM"
BOARD_VENDOR="olimex"
BOARDFAMILY="sun5i"
BOOTCONFIG="A13-OLinuXino_defconfig"
KERNEL_TARGET="current,edge"
FULL_DESKTOP="no"
BOOT_FDT_FILE="sun5i-a13-olinuxino-micro.dtb"
BOOT_EXTRA_ARGS="console=ttyS0,115200 earlycon earlyprintk clk_ignore_unused cpufreq.default_governor=powersave net.ifnames=0 biosdevname=0"

