# Rockchip RK3582 SoC octa core 4-16GB SoC eMMC USB3
BOARD_NAME="Radxa E52C"
BOARDFAMILY="rockchip-rk3588"
BOARD_MAINTAINER="amazingfate"
BOOTCONFIG="radxa-e52c-rk3588s_defconfig"
KERNEL_TARGET="vendor"
BOOT_FDT_FILE="rockchip/rk3588s-radxa-e52c.dtb"
BOOT_SCENARIO="spl-blobs"
BOOT_SOC="rk3588"
IMAGE_PARTITION_TABLE="gpt"
