# Amlogic S905Y2 512MB/1GB/2GB/4GB RAM eMMC USB3 WiFi BT
BOARD_NAME="Radxa Zero"
BOARDFAMILY="meson-g12a"
BOOTCONFIG="radxa-zero_config"
CPUMIN=6660000
CPUMAX=1800000
KERNEL_TARGET="current,edge"
FULL_DESKTOP="yes"
FORCE_BOOTSCRIPT_UPDATE="yes"
BOOT_LOGO="desktop"
ASOUND_STATE="asound.state.radxa-zero"
