# Rockchip RK3328 quad core 2GB RAM SoC WIFI/BT eMMC
BOARD_NAME="RK3328-Heltec"
BOARDFAMILY="rockchip64"
BOARD_MAINTAINER="sicXnull"
BOOTCONFIG="evb-rk3328_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3328-heltec.dtb"
IMAGE_PARTITION_TABLE="gpt"
BOOT_SCENARIO="spl-blobs"
BOOTFS_TYPE="fat"
