# Rockchip RK3399T hexa core 1-4GB SoC GBe eMMC USB3 WiFi/BT PoE
BOARD_NAME="Rock 4SE"
BOARDFAMILY="rockchip64"
BOARD_MAINTAINER=""
BOOTPATCHDIR="v2025.04"
BOOTBRANCH_BOARD="tag:v2025.04"
BOOTCONFIG="rock-4se-rk3399_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3399-rock-4se.dtb"
BOOT_SCENARIO="binman-atf-mainline"
BOOT_SUPPORT_SPI="yes"
