# TI TDA4VM dual core 4GB GBE USB3 OSPI DisplayPort HDMI

BOARD_NAME="SK-TDA4VM"
BOARDFAMILY="k3"
BOARD_MAINTAINER="glneo"
BOOTCONFIG="j721e_evm_a72_defconfig"
BOOTFS_TYPE="fat"
BOOT_FDT_FILE="ti/k3-j721e-sk.dts"
TIBOOT3_BOOTCONFIG="j721e_evm_r5_defconfig"
TIBOOT3_FILE="tiboot3-j721e-gp-evm.bin"
SYSFW_FILE="sysfw-j721e-gp-evm.itb"
DEFAULT_CONSOLE="serial"
KERNEL_TARGET="current,edge"
SERIALCON="ttyS2"
ATF_BOARD="generic"
