# Rockchip RK3328 quad core 1GB-4GB GBE eMMC USB3 WiFi
BOARD_NAME="Station M1"
BOARDFAMILY="rockchip64"
BOOTCONFIG="rock64-rk3328_defconfig"
KERNEL_TARGET="legacy,current,edge"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3328-roc-pc.dtb"
SRC_EXTLINUX="yes"
SRC_CMDLINE="console=uart8250,mmio32,0xff130000 console=tty0"
