# Texas Instruments AM64 dual core 2GB 3xGBE CPSW PRU PCIe OSPI

BOARD_NAME="TMDS64EVM"
BOARD_VENDOR="ti"
BOARDFAMILY="k3"
BOARD_MAINTAINER="jonaswood01"
INTRODUCED="2022"
BOOT_SOC="am64"
BOOTCONFIG="am64x_evm_a53_defconfig"
BOOTFS_TYPE="fat"
BOOT_FDT_FILE="ti/k3-am642-evm.dts"
TIBOOT3_BOOTCONFIG="am64x_evm_r5_defconfig"
TIBOOT3_FILE="tiboot3-am64x_sr2-hs-fs-evm.bin"
DEFAULT_CONSOLE="serial"
HAS_VIDEO_OUTPUT="no"
KERNEL_TARGET="vendor,vendor-rt,vendor-edge,edge"
KERNEL_TEST_TARGET="vendor"
SERIALCON="ttyS2"
ATF_PLAT="k3"
ATF_BOARD="lite"
OPTEE_ARGS=""
OPTEE_PLATFORM="k3-am64x"
TI_PACKAGES+=("firmware-ti-prueth-am64" "firmware-ti-pruhsr-am64" "firmware-ti-pruprp-am64" "firmware-ti-prusw-am64")
