# MB-SMARC-2 with TQMa8MPxS
BOARD_NAME="TQ-SMARC2-TQMa8MPxS"
BOARD_VENDOR="tqgroup"
BOARDFAMILY="imx8m"
BOARD_MAINTAINER="schmiedelm"
INTRODUCED="2025"
HAS_VIDEO_OUTPUT="yes"
ATF_PLAT="imx8mp"
ATF_UART_BASE="0x30880000"
BOOTCONFIG="tqma8mpxs_multi_mb_smarc_2_defconfig"
KERNEL_TARGET="current,edge"
DEFAULT_CONSOLE="serial"
SERIALCON="ttymxc2"
BOOT_FDT_FILE="freescale/imx8mp-tqma8mpqs-mb-smarc-2.dtb"
ASOUND_STATE="asound.state.tqma"
OVERLAY_PREFIX="imx8mp-tqma8mpqs-mb-smarc-2"
