# aarch64 via UEFI/DT for all UEFI-enabled boards
declare -g BOARD_NAME="UEFI/DT arm64"
declare -g BOARD_VENDOR="generic"
declare -g BOARD_MAINTAINER="amazingfate"
declare -g INTRODUCED="2026"
declare -g BOARDFAMILY="uefidt"
declare -g KERNEL_TARGET="edge"
declare -g BOOTCONFIG="none"
declare -g IMAGE_PARTITION_TABLE="gpt"
