# NXP i.MX8M Mini dual/quad Cortex-A53 SoC, 1/2GB RAM, eMMC, GbE, USB, PCIe, MIPI-DSI, MIPI-CSI, optional Wi-Fi/BT
BOARD_NAME="Verdin iMX8M Mini"
BOARD_VENDOR="toradex"
BOARDFAMILY="imx8m"
BOARD_MAINTAINER="lucshl"
INTRODUCED="2020"

KERNEL_TARGET="current"
KERNEL_TEST_TARGET="current"
BOOT_FDT_FILE="freescale/imx8mm-verdin-wifi-dev.dtb"
SERIALCON="ttymxc0"
OVERLAY_PREFIX="verdin-imx8mm"
DEFAULT_OVERLAYS="dsi-to-hdmi" # DSI is the default video out. This makes
                               # testing easier with any hdmi display

BOOTBRANCH="tag:v2026.07"
BOOTPATCHDIR="v2026.07"
BOOTCONFIG="verdin-imx8mm_defconfig"

ATFBRANCH="tag:lts-v2.14.9"
ATF_PLAT="imx8mm"
ATF_UART_BASE="0x30860000"

function post_family_tweaks__verdin_imx8mm_xorg() {
	display_alert "$BOARD" "creating 10-verdin-hdmi.conf" "info"
	mkdir -p "${SDCARD}/etc/X11/xorg.conf.d"
	cat <<- 'XORG_HDMI_CONF' > "${SDCARD}/etc/X11/xorg.conf.d/10-verdin-hdmi.conf"
		Section "ServerFlags"
			Option "AutoAddGPU" "false"
		EndSection

		Section "Device"
			Identifier "Verdin Display"
			Driver "modesetting"
			Option "kmsdev" "/dev/dri/by-path/platform-32e00000.lcdif-card"
			Option "AccelMethod" "none"
		EndSection

		Section "Screen"
			Identifier "Verdin Screen"
			Device "Verdin Display"
		EndSection
	XORG_HDMI_CONF
}
