# Allwinner H618 quad core 1GB/2GB/4GB RAM SoC eMMC WiFi/BT
BOARD_NAME="Walnut Pi Box"
BOARD_VENDOR="walnut"
BOARDFAMILY="sun50iw9"
BOARD_MAINTAINER="TallGuy74"
INTRODUCED="2026"
BOOTCONFIG="walnutpi_box_defconfig"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="sun50i-h618-walnutpi-box.dtb"
OVERLAY_PREFIX="sun50i-h616"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
FORCE_BOOTSCRIPT_UPDATE="yes"
SERIALCON="ttyS0"

enable_extension "uwe5622-allwinner"
