# Xiaomi Snapdragon 8 Gen 2 tablet
BOARD_VENDOR="xiaomi"
BOARD_NAME="Xiaomi Pad 6S Pro"
BOARDS_PRODUCT_URL="https://www.mi.com"
BOARDS_DOCUMENTATION_URL="https://docs.armbian.com"

ARCHITECTURE=arm64
SOCTYPE=qcom
BOOT_LOGO=yes

LINUXFAMILY=qcom-sm8550
KERNEL_TARGET="edge"

IMAGE_PARTITION_TABLE="gpt"

PACKAGE_LIST_BOARD="qrtr-tools modemmanager wpa_supplicant firmware-ath12k"

AVAILABLE_DESKTOPS="gnome kde xfce cli"
