# Rockchip RK3568 quad core 1-8GB SoC 2x1GBe eMMC USB3
BOARD_NAME="YouYeeToo YY3568"
BOARDFAMILY="rk35xx"
BOARD_MAINTAINER="hqnicolas"
BOOTCONFIG="yy3568-rk3568_defconfig"
KERNEL_TARGET="current,edge,vendor"
KERNEL_TEST_TARGET="current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3568-yy3568.dtb"
BOOT_SCENARIO="spl-blobs"
IMAGE_PARTITION_TABLE="gpt"
