# RK3328 quad core SoC 2GB/16GB Gbit WiFi
BOARD_NAME="Z28 PRO"
BOARDFAMILY="rk3328"
BOOTCONFIG="rock64-rk3328_defconfig"
#
MODULES=""
MODULES_NEXT=""
#
KERNEL_TARGET="default"
CLI_TARGET=""
DESKTOP_TARGET="stretch:default"
#
CLI_BETA_TARGET=""
DESKTOP_BETA_TARGET=""
