# RK3328 quad core SoC 2GB/16GB Gbit WiFi BT
BOARD_NAME="Z28 PRO"
BOARDFAMILY="rockchip64"
BOOTCONFIG="rock64-rk3328_defconfig"
#
MODULES=""
MODULES_NEXT=""
#
KERNEL_TARGET="default"
CLI_TARGET="stretch:default"
DESKTOP_TARGET="stretch:default"
#
CLI_BETA_TARGET=""
DESKTOP_BETA_TARGET=""
