name: "Data: Sync labels"
run-name: Sync Labels from YML on ${{ github.event_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
  pull_request:
    paths:
      - ".github/labels.yml"

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read # for actions/labeler to determine modified files
      pull-requests: write # for actions/labeler to add labels to PRs
      issues: write # for actions/labeler to add labels to issues

    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
          exclude: |
            Maintenance*
