name: "Maintenance: Welcome first-time issue contributor"

on:
  issues:
    types: opened

permissions:
  contents: read

jobs:
  welcome-first-time-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@7c31f41b0e7a70adfcae06cf964679f61af6780b # v4.3.0
        with:
          labels: "Good first issue"
          issue-opened-msg: |
            ### Hey @{fc-author}! 👋

            Thanks for opening your first issue with the Armbian project — we’re glad to have you here! 🧡  
            Your input doesn’t just help us improve the project — it benefits everyone who uses Armbian.

            If you'd like to stay informed about project updates or collaborate more closely with the team,  
            you can optionally share some personal contact preferences at [armbian.com/update-data](https://www.armbian.com/update-data/).  
            This helps us keep in touch without relying solely on GitHub notifications.

            Also, don’t forget to ⭐ star the repo to support the work — and welcome aboard! 🚀
